version: "3.8"
services:
  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=aiAppDb
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  aiapp:
    image: aiapp
    container_name: aiapp
    depends_on:
      - postgresql
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgresql:5432/aiAppDb

volumes:
  postgresql_data:
